### ISSUE TITLE
Import javax.servlet

### ISSUE THREAD

**Issue by gregw** [eclipse-ee4j/servlet-api#1]
Import the javax.servlet source and update license headers.

**Comment by gregw** [comment]
The initial code contribution from oracle has been checked in with commit 9ab914730dca550b471955aadaac53675f8458bd by @vinayvishal ,  however:
 - file headers still list APACHE 2.0 licence, so we need to understand exactly how these files will be licensed an update the headers.
 - the contribution here do not include the relevant schemas (currently available from [javaee](https://github.com/javaee/schemas)) and I cannot yet find them elsewhere in [eclipse-ee4j](https://github.com/eclipse-ee4j).
 - the contribution contains no history, branches or tags, this only the 4.0 api is available and the 3.1,3.0, etc. APIs cannot be extracted, let alone built.

**Comment by arjantijms** [comment]
Hi,

The history omission is “correct”. Oracle does not transfer history and
does not transfer branches etc.

This is the same across all transferred code, unfortunately.

Kind regards,
Arjan

**Comment by gregw** [comment]
@arjantijms thanks for that confirmation, I thought as much.  However I think this group needs to determine if being 4.0+ only is satisfactory or if we need to reverse engineer 3.1, 3.0 etc. artifacts?

Any idea on what the official position with schemas is?  Will they be centrally maintained, or will each are get the maintain their own parts?   Have they been contributed anywhere yet?

**Comment by bshannon** [comment]
Much of the Servlet API is derived from Apache Tomcat, and thus uses the Apache license.

The Java EE schemas are [here](https://github.com/javaee/schemas).  A similar repository will be contributed to the (not yet created) Eclipse Jakarta EE Platform project, without all the history.
