### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/servlet-api#194]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by m0mus** [comment]
@markt-asf shall I assign this issue to you?

**Comment by markt-asf** [comment]
@m0mus If you wish. Assignee isn't something I generally pay much attention to in my open source work. I tend to find it discourages participation much more than it prevents duplication of work.

**Comment by markt-asf** [comment]
We have the instance. Next up is creating a build for master.

**Comment by eldermoraes** [comment]
I'm catching up today. Hope to have it done until the end of the week.

It's just a little unclear to me how can I build the job as a non-committer...

**Comment by markt-asf** [comment]
The short version is you can't. I should get to this tomorrow.

**Comment by markt-asf** [comment]
The build pipeline for the master is and and running and the build is green. I'm sure we'll find things we want to tweak as we go along but the basics are there.
