### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/servlet-api#195]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by eldermoraes** [comment]
Hi Dimitry,

I would love to be the responsible person for this one. Can I?

**Comment by m0mus** [comment]
I am fine it you take it. 
@gregw @stuartwdouglas do you have any objections?

**Comment by stuartwdouglas** [comment]
No objections here

**Comment by m0mus** [comment]
@eldermoraes You can start working on it.

**Comment by eldermoraes** [comment]
Great! Thanks.

**Comment by stuartwdouglas** [comment]
BZ to track the provisioning CI: https://bugs.eclipse.org/bugs/show_bug.cgi?id=538596

**Comment by markt-asf** [comment]
First pass has been created for this. Now waiting on Webmaster team to create credentials etc. We also need additional versions of Java install so we can build with the correct one (Java 8 for Servlet 4.0).

**Comment by eldermoraes** [comment]
I'm catching up today. Hope to have it done until the end of the week.

It's just a little unclear to me how can I build the job as a non-committer...

**Comment by markt-asf** [comment]
The short version is you can't. You need to be a project committer to get access to the Jenkins instance.

**Comment by eldermoraes** [comment]
Hmmmmm... ok! So basically I can't contribute in this case, right?

**Comment by markt-asf** [comment]
On the Jenkins jobs, no. However if you are following the various EE4J lists or other projects (e.g. EL , WebSocket or JSP are ones where I know you'll find this stuff) you will see there are lots of requirements to be met for an Eclipse release that this project doesn't currently meet. Issues and PRs for those tasks will help towards getting the first release out.

**Comment by arjantijms** [comment]
Job created and runs. Branch https://github.com/eclipse-ee4j/servlet-api/tree/4.0.2. created by servlet   bot.
