### ISSUE TITLE
HTTP/2 Server Push

### ISSUE THREAD

**Issue by Erik1** [eclipse-ee4j/servlet-api#196]
Why is there chosen that HttpServletRequest#newPushBuilder returns null by default and not to return `Optional<PushBuilder>`?

**Comment by markt-asf** [comment]
The short answer is that it was never considered by the Servlet EG. You can see the full discussion on this part of the API starting here:
http://download.oracle.com/javaee-archive/servlet-spec.java.net/jsr369-experts/2017/01/0491.html

My personal view, with the benefit of hindsight, is that I don't think using an Optional would have improved the API. I'm sure others will have a different view.

Ultimately, there is little point debating the merits of what this API should have been. This part of the API is essentially fixed now - assuming Jakarta EE takes a broadly similar approach to backwards compatibility as has been seen in Java EE to date.
