### ISSUE TITLE
why cannot i find 4.0.2 in maven repository

### ISSUE THREAD

**Issue by lidong14** [eclipse-ee4j/servlet-api#223]
i cannot find 4.0.2 by maven use below：
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <packaging>jar</packaging>
    <version>4.0.2</version>

**Comment by arjantijms** [comment]
It's currently here:

https://oss.sonatype.org/content/repositories/staging/jakarta/servlet/jakarta.servlet-api/4.0.2/

**Comment by lidong14** [comment]
@arjantijms why donot you  put it in maven repository?

**Comment by arjantijms** [comment]
The staging repo is a maven repository. If you add that repo to your pom you can already use it. The other EE4J projects have been recently updated to do just that. They're all in staging now.

**Comment by lidong14** [comment]
@arjantijms thanks,we prepare to add it

**Comment by markt-asf** [comment]
Note that what is in the staging repo is NOT a formal release and has NOT passed the TCK. I strongly recommend waiting for the formal release that will be pushed to Maven central.

**Comment by arjantijms** [comment]
Indeed, what Mark says. All the artefacts are in staging, which is indicative of a pre-release version, mostly added so other artefacts can depend on each other.

If @lidong14 wants to help TESTING it (which I assumed) you can add the staging repository. Needless to say this should NOT be used for anything else than testing.
