### ISSUE TITLE
ServletOutput.println violates Async Writer contract

### ISSUE THREAD

**Issue by gregw** [eclipse-ee4j/servlet-api#228]
The [ServletOutput.println](https://github.com/eclipse-ee4j/servlet-api/blob/master/src/main/java/javax/servlet/ServletOutputStream.java#L191-L194) methods are implemented as follows:
```java
    public void println(String s) throws IOException {
        print(s);
        println();
    }
```
This violates the API contract for asynchronous writers because isReady() needs to be called before every write/print.  In this case the `print(s)` may fill a buffer, which is flushed and hits TCP/IP congestion. The output stream is now not ready, but the `println()` call is made regardless!

**Comment by joakime** [comment]
Couldn't the implementation be changed (or as a workaround, be overridden) to ...

``` java
    public void println(String s) throws IOException {
        print(s + System.lineSeparator());
    }
```

**Comment by gregw** [comment]
@joakime that would work, although it's not that efficient.... it would be better to add the line separator as the string is converted to a byte arrray.... oh wait there is another problem with [print(String)](https://github.com/eclipse-ee4j/servlet-api/blob/master/src/main/java/javax/servlet/ServletOutputStream.java#L63-L85) as it does the string to byte conversion character by character, with write(byte) calls inbetween.   This also violates the async write contract!
