### ISSUE TITLE
CTS ServletTCK httpupgradehandler#upgradeTest fails with Interrupted Exception

### ISSUE THREAD

**Issue by anajosep** [eclipse-ee4j/servlet-api#232]
Test Name:
com/sun/ts/tests/servlet/api/javax_servlet_http/httpupgradehandler#upgradeTest
Error logs:
[ServletTestUtil] Scanning response for search string: 'TCKHttpUpgradeHandler.init' starting at index location: 0
[ServletTestUtil] Found search string: 'TCKHttpUpgradeHandler.init' at index '286' in the server's response
01-06-2019 20:23:57:  ==============Received first expected response!

[ServletTestUtil] Scanning response for search string: 'onDataAvailable' starting at index location: 0
[ServletTestUtil] Found search string: 'onDataAvailable' at index '246' in the server's response
[ServletTestUtil] Scanning response for search string: 'Hello' starting at index location: 261
[ServletTestUtil] Found search string: 'Hello' at index '264' in the server's response
01-06-2019 20:23:57:  ==============Received second expected response!

[ServletTestUtil] Scanning response for search string: 'onDataAvailable' starting at index location: 0
[ServletTestUtil] Found search string: 'onDataAvailable' at index '246' in the server's response
[ServletTestUtil] Scanning response for search string: 'World' starting at index location: 261
[ServletTestUtil] Found search string: 'World' at index '333' in the server's response
01-06-2019 20:23:57:  ==============Received third expected response!

result: Error. Program `/opt/jdk1.8.0_192/jre/bin/java' interrupted! (timed out?)

**Comment by markt-asf** [comment]
This is an issue with the implementation (which isn't identified in the above report) not with the API. Please raise any concerns you have regarding this failure with the implementation that you were running the CTS against.
