### ISSUE TITLE
Fix javax.servlet.http.HttpServletMapping.getMapping javadoc about return value when using DEFAULT servlet

### ISSUE THREAD

**Issue by juangon** [eclipse-ee4j/servlet-api#233]
[HttpServletMapping](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletMapping.html) getPattern method states the following about DEFAULT:

> If the getMappingMatch value is CONTEXT_ROOT or DEFAULT, this method must return the empty string

When reading the same javadoc few lines before, there is a table where slash pattern is written:

> URI Path (in quotes) | matchValue | pattern | mappingMatch
> -- | -- | -- | --
> "" | "" | "" | CONTEXT_ROOT
> "/index.html" | "" | / | DEFAULT
> "/MyServlet" | MyServlet | /MyServlet | EXACT
> "/foo.extension" | foo | *.extension | EXTENSION
> "/path/foo" | foo | /path/* | PATH
> 

Additionally, In servlet 4 spec., section 12.2 says:

> A string containing only the ’ / ’ character indicates the "default" servlet of the
application

So, this collides with HttpServletMapping.getPattern statement.

If both values (empty and "/") are valid for DEFAULT servlet, then this should be written in method's javadoc.

**Comment by arjantijms** [comment]
Thanks for the report. That's indeed an error in the javadoc. 

The pattern is "" respectively /, while the match value is "" in both cases. so getPattern should only say that for CONTEXT_ROOT the empty string should be returned.

**Comment by markt-asf** [comment]
See PR #234
