### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/servlet-api#235]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by arjantijms** [comment]
Project review was success: https://projects.eclipse.org/projects/ee4j.servlet/reviews/4.0.2-release-review

There are no dependencies for the Servlet API.

The staged artefact had disappeared, so I'll re-stage that.

**Comment by arjantijms** [comment]
Servlet 4.0.2 has landed in central:

https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/4.0.2/
