### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cowwoc** [eclipse-ee4j/servlet-api#237]
In https://github.com/eclipse-ee4j/servlet-api/blob/623fbfb4593d0bf07ff9cff6de745f92fa58616f/src/main/java/javax/servlet/ServletRequest.java#L95

"ir is greater than" should be replaced by "**or** is greater than"

**Comment by markt-asf** [comment]
See PR #238 for proposed fix.

**Comment by cowwoc** [comment]
Looks good to me.

**Comment by markt-asf** [comment]
Fix in master
