### ISSUE TITLE
Jakarta EE 8 TCK job

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/servlet-api#241]
To test Jakarta EE 8 compatibility we need to create a Jenkins job on project's Cloud Jenkins instance formally testing the API against the relevant TCK and as needed, relevant CTS subset tests. 

For projects that do not already have automated testing, there is provided parameterized Jenkins job that can be invoked to perform these tests. User provides a link to an Eclipse GlassFish test build and sets the test sub-set parameters:

- For CTS -- https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/
- For Stand-alone TCKs -- https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/

Additional instructions and guidance for using and directly running TCKs is available on [this wiki](https://wiki.eclipse.org/TCK:Build_From_Jakarta_EE_TCK_Repo_And_Run). Also in the [jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck) project repository.

**Comment by markt-asf** [comment]
This looks like it needs to be closed to me. There is no implementation in this project to run the TCK against.

**Comment by m0mus** [comment]
In this case full CTS must be run on glassfish bundle with updated servlet api.

**Comment by arjantijms** [comment]
@m0mus 
> In this case full CTS must be run on glassfish bundle with updated servlet api.

One can update GF 5.1 with the API jar produced by this project, and then run the standalone Servlet TCK against that. The only problem is that the TCK doesn't seem to pass, which is likely "just" a test setup issue.

**Comment by arjantijms** [comment]
* [TCK job](https://jenkins.eclipse.org/servlet/job/2_servlet-run-tck-against-staged-build/)
* [TCK result](https://jenkins.eclipse.org/servlet/job/2_servlet-run-tck-against-staged-build/lastSuccessfulBuild/artifact/servlettck/bin/summary.txt/*view*/)
