### ISSUE TITLE
Update Eclipse GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/servlet-api#255]
Update Eclipse GlassFish to use the new version of your API (and implementation, if applicable) by submitting a PR to [GlassFish](https://github.com/eclipse-ee4j/glassfish).

Although a new version of GlassFish will not be released for Jakarta EE 8, we hope to release an update sometime later.

**Comment by arjantijms** [comment]
https://github.com/eclipse-ee4j/glassfish/pull/22786
