### ISSUE TITLE
Is javax.servlet.SingleThreadModel still relevant in this post Servlet 3.0 world?

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/servlet-api#269]
This is more of a question on what the future of the servlet API will look like.
A future like Jakarta EE 9 or Jakarta EE 10.

Now that it's been a few years on Async Processing and Async I/O, is the old `javax.servlet.SingleThreadModel` still relevant?
Is it time to retire / deprecate `javax.servlet.SingleThreadModel`?
I bet there is little use of that corner of the servlet spec anyway.

**Comment by stuartwdouglas** [comment]
This is already deprecated. I don't really want to remove it unless we have a good reason, as removing it would just potentially cause problems for people without any major upside.

**Comment by arjantijms** [comment]
Of course I respect the methods staying where they are in Servlet, but just wanted to mention that in JSF we did make the decision to remove similarly deprecated things.

**Comment by joakime** [comment]
I have a dream where Jakarta EE 9 or Jakarta EE 10 goes Java 9+ as a minimum JVM.
Then we can start to use the newer `@Deprecated(since="Servlet 2.5", forRemoval="Jakarta EE 10")` in all projects under the Jakarta EE umbrella.

As for this issue, since it's already deprecated, why are we testing for its behavior in the existing TCK?
The other deprecated behaviors (eg: `ServletContext.getRealPath()`) seems to not be tested beyond it's API existence.

**Comment by Thihup** [comment]
Maybe remove the TCK test for Servlet 5.1?
