### ISSUE TITLE
Drop Status Message / Reason Phrase entirely from API

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/servlet-api#305]
Currently we have a deprecation in `HttpServletRequest.setStatus(int, String)` where the status message is ambiguous.

https://github.com/eclipse-ee4j/servlet-api/blob/d8cc005167178b53bf3a6c4a0eeb1270f897411e/api/src/main/java/javax/servlet/http/HttpServletResponse.java#L292-L303

But we don't have a similar deprecation on `.sendError(int, String)`

https://github.com/eclipse-ee4j/servlet-api/blob/d8cc005167178b53bf3a6c4a0eeb1270f897411e/api/src/main/java/javax/servlet/http/HttpServletResponse.java#L122-L147

Seeing as RFC7230 has indicated that the Status Reason Phrase should not be read by Clients ...

https://tools.ietf.org/html/rfc7230#section-3.1.2

>    The reason-phrase element exists for the sole purpose of providing a
>    textual description associated with the numeric status code, mostly
>    out of deference to earlier Internet application protocols that were
>    more frequently used with interactive text clients.  A client SHOULD
>    ignore the reason-phrase content.
> 

And HTTP/2 (as well as HTTP/3) have removed the Status Reason Phrase ...

https://tools.ietf.org/html/rfc7540#section-8.1.2.4

>    HTTP/2 does not define a way to carry the version or reason phrase
>    that is included in an HTTP/1.1 status line.
> 

... it's time to deprecate the status message everywhere it is used in the Servlet spec as well.

**Comment by gregw** [comment]
I think there is a difference between passing on a reason (which should not be supported) and a message (which can be in the body of an error page).

Hence no deprecation on sendError

**Comment by stuartwdouglas** [comment]
Closing, as sendError does not set the reason phrase.
