### ISSUE TITLE
Notification: Jakarta EE 9 Platform TCK pruned Jakarta Deployment specification tests which included removing Servlet NegDep tests

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/servlet-api#324]
Hi @markt-asf @stuartwdouglas 

We removed the following (github.com/eclipse-ee4j/jakartaee-tck) servlet tests, as part of pruning Jakarta Deployment for EE 9 (see [JakartaEE9ReleasePlan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan)).

Please just close this issue as your ack of the deleted tests, unless you have other ideas for bringing the removed tests back.

For removing the Jakarta Deployment tests, we removed src/com/sun/ts/tests/common/negdep/NegdepUtil.java (which depended on javax.enterprise.deploy.spi), along with this, we also removed the (javaeedeploy_optional or javaee_optional) src/com/sun/ts/tests/servlet/ee/platform/negdep test files:

- src/com/sun/ts/tests/servlet/ee/platform/negdep/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/dispatcher/BadDispatcher.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/dispatcher/GoodDispatcher.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/dispatcher/servlet_ee_platform_negdep_enumeration_apps_baddispatcher_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/dispatcher/servlet_ee_platform_negdep_enumeration_apps_gooddispatcher_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/http-method/BadHttpMethod.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/http-method/GoodHttpMethod.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/http-method/servlet_ee_platform_negdep_enumeration_apps_badhttp-method_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/http-method/servlet_ee_platform_negdep_enumeration_apps_goodhttp-method_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/transport-guarantee/BadTransportGuarantee.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/transport-guarantee/GoodTransportGuarantee.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/transport-guarantee/servlet_ee_platform_negdep_enumeration_apps_badtransport-guarantee_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/apps/transport-guarantee/servlet_ee_platform_negdep_enumeration_apps_goodtransport-guarantee_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/ee/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/enumeration/ee/enumerationClient.java
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/jsp-config/BadJspConfig.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/jsp-config/GoodJspConfig.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/jsp-config/servlet_ee_platform_negdep_multi_apps_badjsp-config_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/jsp-config/servlet_ee_platform_negdep_multi_apps_goodjsp-config_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/login-config/BadLoginConfig.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/login-config/GoodLoginConfig.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/login-config/servlet_ee_platform_negdep_multi_apps_badlogin-config_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/login-config/servlet_ee_platform_negdep_multi_apps_goodlogin-config_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/session-config/BadSessionConfig.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/session-config/GoodSessionConfig.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/session-config/servlet_ee_platform_negdep_multi_apps_badsession-config_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/apps/session-config/servlet_ee_platform_negdep_multi_apps_goodsession-config_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/ee/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/multi/ee/multiClient.java
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter-mapping/BadFilterMapping.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter-mapping/GoodFilterMapping.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter-mapping/servlet_ee_platform_negdep_ordering_apps_badfilter-mapping_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter-mapping/servlet_ee_platform_negdep_ordering_apps_goodfilter-mapping_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter/BadFilter.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter/GoodFilter.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter/servlet_ee_platform_negdep_ordering_apps_badfilter_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/filter/servlet_ee_platform_negdep_ordering_apps_goodfilter_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/security-constraint/BadSecurityConstraint.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/security-constraint/GoodSecurityConstraint.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/security-constraint/servlet_ee_platform_negdep_ordering_apps_badsecurity-constraint_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/security-constraint/servlet_ee_platform_negdep_ordering_apps_goodsecurity-constraint_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/servlet/BadServlet.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/servlet/GoodServlet.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/servlet/servlet_ee_platform_negdep_ordering_apps_badservlet_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/apps/servlet/servlet_ee_platform_negdep_ordering_apps_goodservlet_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/ee/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/ordering/ee/orderingClient.java
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/apps/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/apps/newline/BadNewline.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/apps/newline/GoodNewline.war
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/apps/newline/servlet_ee_platform_negdep_urlpattern_apps_badnewline_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/apps/newline/servlet_ee_platform_negdep_urlpattern_apps_goodnewline_web.war.sun-web.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/ee/build.xml
- src/com/sun/ts/tests/servlet/ee/platform/negdep/urlpattern/ee/urlPatternClient.java

**Comment by stuartwdouglas** [comment]
I am fine with removing them, I don't think these tests add a great deal of value. If we were going to update them we would likely need to use Arquillian, but as this TCK does not use Arquillian I don't think it would be worth the effort and additional complexity.

**Comment by markt-asf** [comment]
I agree. No objections to removing them.
