### ISSUE TITLE
Redo images to make them editable (ie. SVG)

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/servlet-api#330]
Just like in the Jakarta EE platform (https://github.com/eclipse-ee4j/jakartaee-platform/issues/214), I think we should redo the images of the specification. Currently is pretty hard to understand the images.

If it is a valid issue, I think redoing it to make them editable as SVG would be terrific.

![image](https://user-images.githubusercontent.com/13357965/86513986-f9d68480-bde4-11ea-8eaf-f9a3cfd37589.png)

**Comment by cpusam** [comment]
The images were created with the program: XSD Diagram:
https://github.com/dgis/xsddiagram
maybe needs some edit on the exported svg, to put some yellow background and some infos.

**Comment by markt-asf** [comment]
That entire section has been dropped form the spec document for 5.0. It duplicates information available in the XSD and adds very little value.
