### ISSUE TITLE
Spec discusses filters as new

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/servlet-api#346]
Just noticed that the spec document described filters as follows:

"New since version 2.4 of the Java Servlet specification is the ability to configure filters to be invoked under request dispatcher forward() and include() calls.

By using the new <dispatcher> element in the deployment descriptor, the developer can indicate for a filter-mapping whether he would like the filter to be applied to requests when:"

Filters aren't really new anymore. I propose to reword this and omit the terms "new" and 'since version".

**Comment by markt-asf** [comment]
This was fixed for Servlet 5.0 onwards.
