### ISSUE TITLE
Tag and commit messages for 5-M2 and 5 releases

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/servlet-api#349]
Somehow the commit and tag comments don't look right... I suppose the job https://ci.eclipse.org/servlet/view/Release/job/1_servlet-build-and-stage/ was not quite properly modified between 5.0.0-M1-RELEASE and 5.0.0-M2-RELEASE. For example https://ci.eclipse.org/servlet/view/Release/job/1_servlet-build-and-stage/53/console:
```
++ mvn -B org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -Pstaging
++ grep -Ev '(^\[)'
+ ARTIFACT_ID='Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
...
jakarta.servlet-api'
++ mvn -B org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.groupId -Pstaging
++ grep -Ev '(^\[)'
+ GROUP_ID='Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
...
jakarta.servlet'
+ STAGING_DESC='Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
...
jakarta.servlet:Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
...
jakarta.servlet-api:5.0.0'
```
Some so funny-set env var is used as commit and tag message
```
-[ Commit modified pom.xml files ]----------------------------------------------
...
+ git commit -m 'Prepare release Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
...
-[ Tag release ]----------------------------------------------------------------
+ git tag 5.0.0-RELEASE -m 'Release Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
...
```

I liked the previous format, used for 5-M1:
```
Prepare release jakarta.servlet:jakarta.servlet-api:5.0.0-M1
```
much better.

I suggest to use `-q` and `-DforceStdout` as arguments to `mvn :maven-help-plugin` call and drop `grep` then.

**Comment by arjantijms** [comment]
I tried it, but it doesn't seem t help:

```
++ mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -q -DforceStdout org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -Pstaging
++ grep -Ev '(^\[)'

+ ARTIFACT_ID='Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /opt/tools/java/oracle/jdk-8/1.8.0_202/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.el7.x86_64", arch: "amd64", family: "unix"
jakarta.servlet-api'


++ mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -q -DforceStdout org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.groupId -Pstaging++ 
grep -Ev '(^\[)'

+ GROUP_ID='Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /opt/tools/java/oracle/jdk-8/1.8.0_202/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.el7.x86_64", arch: "amd64", family: "unix"
jakarta.servlet'
```

**Comment by pzygielo** [comment]
I have no access to sources (of that problem), so I can only guess - that maven's `--show-version` option is activated - maybe in `/home/jenkins/.mavenrc` or in `MAVEN_OPTS`.
I even can't compare with previous (53) build as conveniently only one is available at https://ci.eclipse.org/servlet/view/Release/job/1_servlet-build-and-stage.

**Comment by arjantijms** [comment]
It throws away older ones indeed.

The version is activated via `/home/jenkins/.mavenrc` using the `-V` option:

```
cat /home/jenkins/.mavenrc
set -- -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --batch-mode
```

**Comment by pzygielo** [comment]
```
    - mountPath: "/home/jenkins/.mavenrc"
      name: "m2-dir"
      readOnly: true
      subPath: ".mavenrc"
```
All options set there but `-V` seem to be duplicated by `MVN_EXTRA`.
If this volumeMount can't be dropped, I suggest to set env var:
```
#   MAVEN_SKIP_RC   (Optional) Flag to disable loading of mavenrc files.
```

**Comment by arjantijms** [comment]
I'm afraid the flag doesn't work, and neither does the `-D` option:

```
++ mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.skip.rc=true -q -DforceStdout org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -Pstaging
++ grep -Ev '(^\[)'

+ ARTIFACT_ID='Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/tools/apache-maven/latest
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /opt/tools/java/oracle/jdk-8/1.8.0_202/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.el7.x86_64", arch: "amd64", family: "unix"
jakarta.servlet-api'
```

**Comment by pzygielo** [comment]
I don't know if this is customized maven installation or what.

So it looks like there has to be some hack implemented to get - as we know - the last line of output (and skip the part produced by `-V`) - with something like `tail -n 1` :cry: 
With `grep -Ev '(^\[)'` kept in place - `-q` and `-DforceStdout` can be removed back I think.

I just wonder why `.mavenrc` is used at all, was it used in M1 release, was it modified to add `-V` - and if so - why.

Do other projects have to deal with that goodness of enforced maven version info too?
   - Looks that https://ci.eclipse.org/mail/job/release-staging/ also mounts .mavenrc. But it doesn't rely on maven's output.
   - On the other hand - https://ci.eclipse.org/soteria/job/1_soteria-build-and-stage does, and it's affected [in similar way](https://github.com/eclipse-ee4j/soteria/releases/tag/2.0.0-M3-RELEASE) with [2.0.0-M1-RELEASE](https://github.com/eclipse-ee4j/soteria/releases/tag/2.0.0-M1-RELEASE) looking fine.

I would rather see `-V` (or to be more precise - everything) removed from global mavenrc.

**Comment by pzygielo** [comment]
As for now dozen other EE4J repositories use the same improvement that is reflected in commits/tags.
But one is interesting: [tyrus](https://github.com/eclipse-ee4j/tyrus). It has more than one recent builds preserved.
Comparison of [tyrus-master-release/84](https://ci.eclipse.org/tyrus/job/tyrus-master-release/84) against [tyrus-master-release/87](https://ci.eclipse.org/tyrus/job/tyrus-master-release/87) shows that they differ in `volumeMounts`. 84 didn't mount mavenrc and the commit and tag for tyrus:2.0.0-M2 are fine.

**Comment by arjantijms** [comment]
Probably need to create bug at the Eclipse Bugzilla to have the annoying `-V` removed. That would be in the community -> CI Jenkins section (like e.g. this bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=561229)

**Comment by pzygielo** [comment]
It was already reported https://bugs.eclipse.org/bugs/show_bug.cgi?id=566197 and closed as fixed.
As it is still observable filed new https://bugs.eclipse.org/bugs/show_bug.cgi?id=566505.

**Comment by arjantijms** [comment]
Great, thanks for filling that one. Will monitor it.

**Comment by pzygielo** [comment]
~[566505](https://bugs.eclipse.org/bugs/show_bug.cgi?id=566505)~ was just fixed, with `-V` flag removed from .mavenrc.
I hope it will help with new release. :crossed_fingers:

**Comment by arjantijms** [comment]
Cool! I'm going to try soon, thank you so much for your eye for detail here!

**Comment by pzygielo** [comment]
New [release 5.0.0-RELEASE tag](https://github.com/eclipse-ee4j/servlet-api/releases/tag/5.0.0-RELEASE) and [commit e07dd4b7](https://github.com/eclipse-ee4j/servlet-api/commit/e07dd4b795b42478a5b7363b6801a5fe3318d3e1) look fine.
