### ISSUE TITLE
Completion Steps for Servlet 5.0

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/servlet-api#366]
* Specification Committee Mentor
 - [x] creates an issue in the specification project that includes the following checklist for the specification project team:

* Specification Project Team
 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
@kwsutter For some reason the website won't update after the merge: https://jakarta.ee/specifications/servlet/5.0/

Maybe a job is stuck somewhere?

**Comment by kwsutter** [comment]
> @kwsutter For some reason the website won't update after the merge: https://jakarta.ee/specifications/servlet/5.0/
> 
> Maybe a job is stuck somewhere?

Very strange.  I just merged the updates to the _index.md for the ballot results.  If this doesn't push the changes out to the website, then I will follow up with infra.  Thanks for noticing this!

**Comment by kwsutter** [comment]
> > @kwsutter For some reason the website won't update after the merge: https://jakarta.ee/specifications/servlet/5.0/
> > Maybe a job is stuck somewhere?
> 
> Very strange. I just merged the updates to the _index.md for the ballot results. If this doesn't push the changes out to the website, then I will follow up with infra. Thanks for noticing this!

It's all working now.  I found out that these jakarta.ee website builds are triggered once per day.  The merge I did yesterday was just after the build was triggered, so we just had to be more patient.  In the mean time, I found a way to trigger a build so that I can do this manually if needed in the future.  Bottom line is that the Servlet 5.0 page is now up and running!
https://jakarta.ee/specifications/servlet/5.0/

**Comment by arjantijms** [comment]
The new push did the trick, as it's updated now. Thanks!

**Comment by arjantijms** [comment]
PR for final step: https://github.com/eclipse-ee4j/servlet-api/pull/367

**Comment by kwsutter** [comment]
@arjan, We (Spec Committee) noticed the link for the Compatible Implementation is for a weekly snapshot driver.  Since this "weekly" folder could accidentally be deleted or emptied sometime in the future, it was recommended that this driver get moved to somewhere more permanent.  Even something simple like "keep" folder would suffice.  We are also looking at firming up these instructions for our future PRs and CRs.  Thanks!

**Comment by arjantijms** [comment]
>  Even something simple like "keep" folder would suffice. We are also looking at firming up these instructions for our future PRs and CRs. Thanks!

Interestingly enough, this is indeed what I mentioned before, and why I did some of the other PRs with my "own" stable GlassFish version. If I'm not mistaken, I think I proposed effectively an RC per 2 week period of ballots.

**Comment by kwsutter** [comment]
> > Even something simple like "keep" folder would suffice. We are also looking at firming up these instructions for our future PRs and CRs. Thanks!
> 
> Interestingly enough, this is indeed what I mentioned before, and why I did some of the other PRs with my "own" stable GlassFish version. If I'm not mistaken, I think I proposed effectively an RC per 2 week period of ballots.

Agree that this hasn't been clear.  David took a work item to write up something that we could review and hopefully approve soon.  Nobody is asking or forcing any changes to the Servlet ballot and content.  I'm just pointing out the desired outcome in case you want to get ahead of the curve.  Thanks.

**Comment by arjantijms** [comment]
And all items are checked off, closing this.
