### ISSUE TITLE
Specify behavior when two applications set the same default-context-path

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/servlet-api#379]
I couldn't find any references to what should happen when two applications set the same default-context-path.
Running some test applications across some implementations, the second application fails to deploy.

Maybe add the behavior to the specification?

**Comment by gregw** [comment]
There are many different ways that a server can select between two contexts at the same contextPath:
 - virtual host (ie look at the host header)
 - some kind of connector selector (eg Jetty has a named connector/listener mechanism that can be used to select contexts)
 - some other version based selector that allows requests to be directed to multiple versions of the same webapp.
 - as part of a hot/graceful deploy mechanism, when a new version is added to accept new connections/requests whilst existing connections/requests are drained out of the old context

So I'm not sure there is a general answer to what should happen.

**Comment by stuartwdouglas** [comment]
I don't think this needs to be part of the spec, the context path can be overridden by container specific mechanisms anyway, and as Greg says there are lots of scenarios where you may have two applications with the same context path, with the selection done on something other than path.

**Comment by Thihup** [comment]
Makes sense
