### ISSUE TITLE
TCK Challenge httpServletMappingDispatchTest 

### ISSUE THREAD

**Issue by gregw** [eclipse-ee4j/servlet-api#385]
**Specification:**
 + [Servlet 5.0.0 12.3.1 Runtime Discovery of Servlet Mappings](https://github.com/eclipse-ee4j/servlet-api/blob/5.0.0-RELEASE/spec/src/main/asciidoc/servlet-spec-body.adoc#1231-runtime-discovery-of-servlet-mappings)

**Challenged test(s):**
* [com.sun.ts.tests.servlet.api.jakarta_servlet_http.httpservletrequest40#httpServletMappingDispatchTest](https://github.com/eclipse-ee4j/jakartaee-tck/blob/9.0.0/src/com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest40/Client.java#L210)

**TCK version:**
 * 9.0.0

**Tested implementation:**
[Eclipse Jetty](https://www.eclipse.org/jetty/)

**Description**

The specification for `getHttpServletMapping` says:
> The method getHttpServletMapping() on HttpServletRequest returns an HttpServletMapping implementation that provides information for the mapping that caused the current Servlet to be invoked. Please see the javadocs for the normative specification.

For async dispatch, the javadoc originally said:

> If the currently active `Servlet` invocation was obtained by a call to `javax.servlet.AsyncContext#dispatch`, the returned `HttpServletMapping` is the one corresponding to the path that caused the first `Servlet` in the invocation sequence to be invoked. See `javax.servlet.RequestDispatcher#FORWARD_MAPPING`

However, after discussion in https://github.com/eclipse-ee4j/servlet-api/issues/309 this was updated in https://github.com/eclipse-ee4j/servlet-api/pull/313 to [say](https://github.com/eclipse-ee4j/servlet-api/blob/5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpServletRequest.java#L165-L208):

> The mapping returned depends on the current `jakarta.servlet.DispatcherType` as obtained from `getDispatcherType()`: `REQUEST`, `ASYNC`, `ERROR` : Return the mapping for the target of the dispatch i.e. the mapping for the current `Servlet`.

The test has not yet been updated and is still testing the previous (mis)specified behaviour.

**Comment by scottmarlow** [comment]
@gregw as per https://jakarta.ee/committees/specification/tckprocess, could you please include the full test names/coordinates (see https://github.com/eclipse-ee4j/servlet-api/issues/378 for examples like `com.sun.ts.tests.servlet.api.jakarta_servlet_http.cookie.URLClient#setMaxAgePositiveTest`) to be excluded:

- [x]     The relevant specification version and section number(s)
- [ ]     The coordinates of the challenged test(s)
- [x]     The exact TCK version
- [x]     The implementation being tested, including name and company
- [x]     A full description of why the test is invalid and what the correct behavior is believed to be
- [ ]     Any supporting material; debug logs, test output, test logs, run scripts, etc.

**Comment by gregw** [comment]
@scottmarlow updated

**Comment by scottmarlow** [comment]
@markt-asf  @stuartwdouglas could you please accept or decline this challenge.

**Comment by scottmarlow** [comment]
@gregw I would like to release a `9.0.1` Platform TCK this week for another TCK challenge.  If this challenge is accepted, I will include it.

As per the TCK process, we should expect a timely response to TCK challenges, however, it may take more time as we haven't yet heard from @stuartwdouglas or @markt-asf (perhaps they are on holiday break or something).

**Comment by markt-asf** [comment]
@scottmarlow Sorry, I've been on leave. I wholeheartedly agree with this challenge.

**Comment by scottmarlow** [comment]
Blocked on https://github.com/jakartaee/specifications/issues/321 for releasing Jakarta Servlet TCK 5.0.1 + Jakarta EE Platform TCK 9.0.1

**Comment by scottmarlow** [comment]
This issue can now be closed as https://download.eclipse.org/jakartaee/servlet/5.0/jakarta-servlet-tck-5.0.1.zip + https://download.eclipse.org/jakartaee/platform/9/jakarta-jakartaeetck-9.0.1.zip are published.

https://jakarta.ee/specifications/servlet/5.0/ + https://jakarta.ee/specifications/platform/9/ are updated to link to the ^ published TCKs.

**Comment by markt-asf** [comment]
Closing as per previous comment.
