### ISSUE TITLE
Java 2 security issue with Cookie class

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/servlet-api#389]
When testing some RESTEasy code with Java 2 security enabled, I ran into the following exception:
```
("java.util.PropertyPermission" "org.glassfish.web.rfc2109_cookie_names_enforced" "read")
Stack: 
java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "org.glassfish.web.rfc2109_cookie_names_enforced" "read")java.base/java.security.AccessController.throwACE(AccessController.java:176)
java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
java.base/java.security.AccessController.checkPermission(AccessController.java:385)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
java.base/java.lang.System.getProperty(System.java:489)
jakarta.servlet.http.Cookie.<clinit>(Cookie.java:68)
java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1447)
java.base/java.lang.J9VMInternals.initialize(J9VMInternals.java:127)
java.base/java.lang.Class.forName(Class.java:351)
com.sun.proxy.$Proxy43.<clinit>(Unknown Source)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1022)
java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1008)
org.jboss.resteasy.core.ContextParameterInjector.createProxy(ContextParameterInjector.java:195)
org.jboss.resteasy.core.ContextParameterInjector.inject(ContextParameterInjector.java:164)
org.jboss.resteasy.core.PropertyInjectorImpl.inject(PropertyInjectorImpl.java:208)
org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.injectedInstance(ResteasyProviderFactoryImpl.java:1412)
org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$AbstractInterceptorFactory.createInterceptor(JaxrsInterceptorRegistryImpl.java:150)
org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.initialize(JaxrsInterceptorRegistryImpl.java:168)
org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.checkInitialize(JaxrsInterceptorRegistryImpl.java:183)
org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.getInterceptor(JaxrsInterceptorRegistryImpl.java:194)
org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$AbstractInterceptorFactory.postMatch(JaxrsInterceptorRegistryImpl.java:138)
org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl.postMatch(JaxrsInterceptorRegistryImpl.java:283)
org.jboss.resteasy.client.jaxrs.internal.ClientConfiguration.getRequestFilters(ClientConfiguration.java:120)
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.getRequestFilters(ClientInvocation.java:454)
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:675)
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:485)
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:65)
org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:190)
com.ibm.samples.jaxrs.HelloRest20ClientServlet.doGet(HelloRest20ClientServlet.java:52)
jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257)
```

The culprit is https://github.com/eclipse-ee4j/servlet-api/blob/f9da4fb827d8aff62641e76931e3212f7b136b2e/api/src/main/java/jakarta/servlet/http/Cookie.java#L68 - calls to `System.getProperty(...)` may throw a SecurityException.  Could we put the `getProperty(...)` call into a doPriv block?

I'd be willing to open a PR with a proposed fix.  Thanks!

**Comment by martin-g** [comment]
Why Glassfish specific code is in the API ?!

**Comment by andymc12** [comment]
> Why Glassfish specific code is in the API ?!

I suspect that it is an artifact of the "old days" where there were references to the reference implementation. I know we used to lookup GlassFish/Jersey code from the JAX-RS APIs.  Most of that is cleaned up, but I have seen RI references in other Jakarta EE 9 projects too.

My proposed change was just to put it in a doPriv - but maybe for a future release this property should be replaced with something less specific to a particular implementation - maybe:
`if (Boolean.valueOf(System.getProperty("jakarta.servlet.rfc2109_cookie_names_enforced", "true"))` ?

**Comment by pzygielo** [comment]
As https://github.com/javaee/servlet-spec/commit/334ace8219603405bc4ffdf80e635e1e61cc1cc4: _until Woodstock has been fixed_ 
Perhaps after 11 years this hack is no longer needed and could be removed completely?

**Comment by martin-g** [comment]
Yes, IMO this would be better!

**Comment by stuartwdouglas** [comment]
I don't really think the constructor of an API class is the correct place for this check anyway. Implementation should check it when the cookie is added.

**Comment by markt-asf** [comment]
As we saw with the TCK challenge, there are some aspects of cookie support that need cleaning up. Consistently mandating RFC 6265 would address multiple issues - including this one (it would remove the need for this check).
Performing the check in the constructor allows us to fail early - which is good - but makes it pretty much impossible for any implementation to offer a configuration option to relax the check. Given the history of poor adherence to the cookie specs I suspect such an option may be considered necessary by some users. I'm torn as to which is the best approach here.

**Comment by stuartwdouglas** [comment]
I don't think the 'fail early' advantage is real, as 99% of the time if you create a cookie then you immediately add it to the response, so the failure point will be basically the same.

System properties from static init blocks have caused lots of problems for us in the past, as they are read when the class is initialized, so if you accidently initialize the class before your management layer has figured out that this property needs to be set then it just won't take effect, and configuration via passing lots of system properties on the command line is not user friendly or practical.

**Comment by andymc12** [comment]
I love the discussion on this - I'm glad to have helped kick it off!  But maybe there are two issues here:
* For future releases, this will need a more elegant solution - it could be (1) converting the property to `jakarta.*`, (2) mandating RFC 6265 (and thus deleting this check), (3) providing an alternate mechanism to relax the check, (4) or something else that we haven't discussed or that I missed in the discussion so far.
* For the EE9 / servlet 5.0 release, I think the only right answer is to wrap the existing property check in a doPriv block.  Otherwise, we could be breaking existing implementations in a patch release.

Would it make sense for me to open a separate issue for the EE9 / servlet 5.0 release?  That way we could continue the conversation here for the next release.

**Comment by stuartwdouglas** [comment]
I have opened a PR that just fixes the security manager issue.
