### ISSUE TITLE
Compatibility certification request for Eclipse Jetty for Servlet 5 on EE9

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse-ee4j/servlet-api#394]
- [X] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Jetty, https://www.eclipse.org/jetty/
- [X] Product Name, Version and download URL (if applicable):<br/>
  Jetty 11.0.1, https://www.eclipse.org/jetty/download.php
- [X] Specification Name, Version and download URL:<br/>
   Jakarta Servlet 5.0     https://jakarta.ee/specifications/servlet/5.0/
- [X] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
 Servlet TCK 5.0.1  https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/servlet-tck-5.0.1.zip   SHA256SUM: 915e269802a39a71b006d8beb62ebece74a1bb6586d5d2bebf60f7ab4d123a5b
- [X] Public URL of TCK Results Summary:<br/>
  https://jenkins.webtide.net/job/tck/job/servlettck-run-jetty-11.0.x/lastCompletedBuild/TCK_20Report/
- [X] Any Additional Specification Certification Requirements:<br/>
  N/A
- [X] Java runtime used to run the implementation:<br/>
  JDK 8
- [X] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Unbuntu
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by gregw** [comment]
@markt-asf @stuartwdouglas What is the voting process for this?  If it is just comments, then I'm a +1, unless I'm not meant to vote due to my interest in the outcome?

**Comment by markt-asf** [comment]
I think 2 weeks lazy consensus or a +1 from a project lead. Looks good to me so +1

**Comment by ivargrimstad** [comment]
@markt-asf @gregw You're right. The process outlined in the [TCK Process](https://jakarta.ee/committees/specification/tckprocess/) is either:
* Approval by lazy consensus after a period of two weeks (14 days)
* Approval by a majority vote of the specification project as soon as it happens.
  * The sum of the +1/-1 votes must be greater than 50% of the specification project committers.
* Approval by any top-level specification project lead at any time

Please add the `accepted` label to this issue when the request is approved.

**Comment by stuartwdouglas** [comment]
LGTM, so I am also giving a +1

**Comment by arjantijms** [comment]
+1, great work Greg and team!

**Comment by gregw** [comment]
@arjantijms thanks!  After decades of being kind-of-compliant and sort-of-TCK-aware, it's good to finally be inside the tent!

**Comment by markt-asf** [comment]
Marking as accepted.
