### ISSUE TITLE
Add support for registering a custom URLStreamHandler

### ISSUE THREAD

**Issue by Horcrux7** [eclipse-ee4j/servlet-api#432]
Because `URL.setURLStreamHandlerFactory(x)` can called only once this method can't use from an application inside of an application server.

Also the service loading via `com.inet.lib.io.URLProtocolManagerURLStreamHandlerProvider` does not work because the application is not on the root classpath.

There already different proprietary solution in different application servers for registering a custom `URLStreamHandler`.

There should be a standard solution.

**Comment by markt-asf** [comment]
Closing in preference to the platform spec issue.
